import type { MenuItemType } from './types';

export const menuData: MenuItemType[] = [
  {
    id: '1',
    name: 'Classic Cheeseburger',
    description: 'A juicy beef patty with melted cheddar cheese, lettuce, tomato, and our special sauce.',
    price: 9.99,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'cheeseburger classic',
    category: 'Burgers',
    customizationOptions: [
      {
        id: 'extra-patty',
        name: 'Add Extra Patty',
        type: 'single',
        choices: [
          { name: 'No', priceModifier: 0 },
          { name: 'Yes', priceModifier: 2.50 },
        ],
      },
      {
        id: 'extra-cheese',
        name: 'Add Extra Cheese',
        type: 'single',
        choices: [
          { name: 'No', priceModifier: 0 },
          { name: 'Yes', priceModifier: 1.00 },
        ],
      },
    ],
  },
  {
    id: '2',
    name: 'Bacon Avocado Burger',
    description: 'Topped with crispy bacon, fresh avocado, Swiss cheese, and a zesty aioli.',
    price: 12.99,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'bacon burger',
    category: 'Burgers',
    customizationOptions: [
      {
        id: 'extra-bacon',
        name: 'Add Extra Bacon',
        type: 'single',
        choices: [
          { name: 'No', priceModifier: 0 },
          { name: 'Yes', priceModifier: 1.50 },
        ],
      },
    ],
  },
  {
    id: '3',
    name: 'Spicy Jalapeño Burger',
    description: 'For those who like it hot! A fiery burger with jalapeños, pepper jack cheese, and chipotle mayo.',
    price: 11.99,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'spicy burger',
    category: 'Burgers',
     customizationOptions: [
      {
        id: 'heat-level',
        name: 'Heat Level',
        type: 'single',
        choices: [
          { name: 'Spicy (Standard)', priceModifier: 0 },
          { name: 'Extra Spicy', priceModifier: 0.50 },
          { name: 'Volcanic', priceModifier: 1.00 },
        ],
      },
    ],
  },
  {
    id: '4',
    name: 'Margherita Pizza',
    description: 'Classic pizza with fresh mozzarella, San Marzano tomatoes, fresh basil, salt, and extra-virgin olive oil.',
    price: 14.99,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'margherita pizza',
    category: 'Pizzas',
    customizationOptions: [
        {
            id: 'size',
            name: 'Size',
            type: 'single',
            choices: [
                { name: 'Маленькая (20 cm)', priceModifier: 0 },
                { name: 'Средняя (30 cm)', priceModifier: 4.00 },
                { name: 'Большая (40 cm)', priceModifier: 8.00 },
            ],
        },
        {
            id: 'crust',
            name: 'Crust',
            type: 'single',
            choices: [
                { name: 'традиционная', priceModifier: 0 },
                { name: 'тонкая', priceModifier: 0 },
            ],
        },
        {
            id: 'toppings',
            name: 'Extra Toppings',
            type: 'multiple',
            choices: [
                { name: 'Mushrooms', priceModifier: 1.25 },
                { name: 'Olives', priceModifier: 1.25 },
                { name: 'Extra Basil', priceModifier: 1.00 },
            ],
        },
    ],
  },
  {
    id: '5',
    name: 'Pepperoni Pizza',
    description: 'An American classic with a generous amount of pepperoni and mozzarella cheese.',
    price: 16.99,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'pepperoni pizza',
    category: 'Pizzas',
    customizationOptions: [
      {
        id: 'size',
        name: 'Size',
        type: 'single',
        choices: [
            { name: 'Маленькая (20 cm)', priceModifier: 0 },
            { name: 'Средняя (30 cm)', priceModifier: 4.00 },
            { name: 'Большая (40 cm)', priceModifier: 8.00 },
        ],
    },
    {
        id: 'crust',
        name: 'Crust',
        type: 'single',
        choices: [
            { name: 'традиционная', priceModifier: 0 },
            { name: 'тонкая', priceModifier: 0 },
        ],
    },
    ],
  },
  {
    id: '6',
    name: 'BBQ Chicken Pizza',
    description: 'Topped with tangy BBQ sauce, grilled chicken, red onions, and cilantro.',
    price: 18.99,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'bbq pizza',
    category: 'Pizzas',
    customizationOptions: [
      {
        id: 'size',
        name: 'Size',
        type: 'single',
        choices: [
            { name: 'Маленькая (20 cm)', priceModifier: 0 },
            { name: 'Средняя (30 cm)', priceModifier: 4.00 },
            { name: 'Большая (40 cm)', priceModifier: 8.00 },
        ],
    },
    {
        id: 'crust',
        name: 'Crust',
        type: 'single',
        choices: [
            { name: 'традиционная', priceModifier: 0 },
            { name: 'тонкая', priceModifier: 0 },
        ],
    },
    ],
  },
  {
    id: '7',
    name: 'French Fries',
    description: 'Crispy, golden-brown fries salted to perfection. The perfect side for any meal.',
    price: 3.99,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'french fries',
    category: 'Sides',
    customizationOptions: [
        {
            id: 'seasoning',
            name: 'Seasoning',
            type: 'single',
            choices: [
                { name: 'Regular Salt', priceModifier: 0 },
                { name: 'Cajun Spice', priceModifier: 0.50 },
                { name: 'Garlic Parmesan', priceModifier: 0.75 },
            ],
        },
    ],
  },
  {
    id: '8',
    name: 'Onion Rings',
    description: 'Thick-cut onion rings, battered and fried until golden and crispy.',
    price: 4.99,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'onion rings',
    category: 'Sides',
  },
  {
    id: '9',
    name: 'House Salad',
    description: 'A fresh mix of greens, tomatoes, cucumbers, and croutons with your choice of dressing.',
    price: 5.99,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'house salad',
    category: 'Sides',
  },
  {
    id: '10',
    name: 'Cola',
    description: 'A refreshing can of classic cola.',
    price: 1.99,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'cola drink',
    category: 'Drinks',
    customizationOptions: [
        {
            id: 'size',
            name: 'Size',
            type: 'single',
            choices: [
                { name: 'Can (12oz)', priceModifier: 0 },
                { name: 'Bottle (20oz)', priceModifier: 0.80 },
            ],
        },
    ],
  },
  {
    id: '11',
    name: 'Lemonade',
    description: 'Freshly squeezed lemonade, perfectly sweet and tart.',
    price: 2.49,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'lemonade drink',
    category: 'Drinks',
    customizationOptions: [
        {
            id: 'size',
            name: 'Size',
            type: 'single',
            choices: [
                { name: 'Regular (16oz)', priceModifier: 0 },
                { name: 'Large (24oz)', priceModifier: 1.00 },
            ],
        },
    ],
  },
  {
    id: '12',
    name: 'Iced Tea',
    description: 'Brewed fresh daily, available sweetened or unsweetened.',
    price: 2.29,
    image: 'https://picsum.photos/600/400',
    'data-ai-hint': 'iced tea',
    category: 'Drinks',
    customizationOptions: [
        {
            id: 'size',
            name: 'Size',
            type: 'single',
            choices: [
                { name: 'Regular (16oz)', priceModifier: 0 },
                { name: 'Large (24oz)', priceModifier: 1.00 },
            ],
        },
    ],
  },
  {
    id: '13',
    name: 'Омлет с ветчиной и грибами',
    description: 'A delicious omelette with ham and mushrooms.',
    price: 7.99,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE7970321044479C1D1085457A36EB.webp',
    category: 'Breakfast',
  },
  {
    id: '14',
    name: 'Омлет с пепперони',
    description: 'A tasty omelette with pepperoni.',
    price: 8.49,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE94ECF33B0C46BA410DEC1B1DD6F8.webp',
    category: 'Breakfast',
  },
  {
    id: '15',
    name: 'Кофе Латте',
    description: 'Freshly brewed Caffe Latte.',
    price: 3.99,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE7D61B0C26A3F85D97A78FEEE00AD.webp',
    category: 'Breakfast',
  },
  {
    id: '16',
    name: 'Дэнвич ветчина и сыр',
    description: 'A delicious ham and cheese denwich.',
    price: 6.99,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE796FF0059B799A17F57A9E64C725.webp',
    category: 'Snacks',
  },
  {
    id: '17',
    name: 'Куриные наггетсы',
    description: 'Crispy chicken nuggets.',
    price: 5.99,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE7D618B5C7EC29350069AE9532C6E.webp',
    category: 'Snacks',
  },
  {
    id: '18',
    name: 'Картофель из печи с соусом 🌱',
    description: 'Oven-baked potatoes with sauce.',
    price: 4.99,
    image: 'https://media.dodostatic.net/image/r:292x292/11EED646A9CD324C962C6BEA78124F19.webp',
    category: 'Snacks',
  },
  {
    id: '19',
    name: 'Додстер',
    description: 'A classic dodster.',
    price: 6.49,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE796F96D11392A2F6DD73599921B9.webp',
    category: 'Snacks',
  },
  {
    id: '20',
    name: 'Острый Додстер 🌶️🌶️',
    description: 'A spicy dodster for those who like it hot.',
    price: 6.99,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE796FD3B594068F7A752DF8161D04.webp',
    category: 'Snacks',
  },
  {
    id: '21',
    name: 'Банановый молочный коктейль',
    description: 'A refreshing banana milkshake.',
    price: 4.99,
    image: 'https://media.dodostatic.net/image/r:292x292/11EEE20B8772A72A9B60CFB20012C185.webp',
    category: 'Drinks',
  },
  {
    id: '22',
    name: 'Карамельное яблоко молочный коктейль',
    description: 'A delicious caramel apple milkshake.',
    price: 5.49,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE79702E2A22E693D96133906FB1B8.webp',
    category: 'Drinks',
  },
  {
    id: '23',
    name: 'Молочный коктейль с печеньем Орео',
    description: 'A classic Oreo cookie milkshake.',
    price: 5.49,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE796FA1F50F8F8111A399E4C1A1E3.webp',
    category: 'Drinks',
  },
  {
    id: '24',
    name: 'Классический молочный коктейль 👶',
    description: 'A classic milkshake.',
    price: 4.49,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE796F93FB126693F96CB1D3E403FB.webp',
    category: 'Drinks',
  },
  {
    id: '25',
    name: 'Ирландский Капучино',
    description: 'A rich and creamy Irish Cappuccino.',
    price: 4.99,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE7D61999EBDA59C10E216430A6093.webp',
    category: 'Drinks',
  },
  {
    id: '26',
    name: 'Кофе Карамельный капучино',
    description: 'A sweet and creamy caramel cappuccino.',
    price: 5.49,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE7D61AED6B6D4BFDAD4E58D76CF56.webp',
    category: 'Drinks',
  },
  {
    id: '27',
    name: 'Кофе Кокосовый латте',
    description: 'A tropical twist on a classic latte.',
    price: 5.49,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE7D61B19FA07090EE88B0ED347F42.webp',
    category: 'Drinks',
  },
  {
    id: '28',
    name: 'Кофе Американо',
    description: 'A classic Americano coffee.',
    price: 3.49,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE7D61B044583596548A59078BBD33.webp',
    category: 'Drinks',
  },
  {
    id: '29',
    name: 'Кофе Латте',
    description: 'A smooth and creamy Caffe Latte.',
    price: 4.49,
    image: 'https://media.dodostatic.net/image/r:292x292/11EE7D61B0C26A3F85D97A78FEEE00AD.webp',
    category: 'Drinks',
  },
];
